const path = './';

export const Images = {
  profilPic: require(`${path}profilPic.jpg`),
  rating: require(`${path}rating.png`),
  politics: require(`${path}politics.jpg`),
  business: require(`${path}business.jpg`),
  programming: require(`${path}programming.png`),
  profil: require(`${path}profil.png`),
  profilBlack: require(`${path}profil_black.png`),
  settings: require(`${path}settings.png`),
  settingsBlack: require(`${path}settings_black.png`),
  meetings: require(`${path}meetings.png`),
  meetingsBlack: require(`${path}meetings_black.png`),
  home: require(`${path}home.png`),
  homeBlack: require(`${path}home_black.png`),
  address: require(`${path}address.png`),
  addressBlack: require(`${path}addressBlack.png`),
  chat: require(`${path}chat.png`),
  chatBlue: require(`${path}chatBlue.png`),
  phone: require(`${path}phone.png`),
  phoneBlack: require(`${path}phoneBlack.png`),
  mail: require(`${path}mail.png`),
  addToGroup: require(`${path}addToGroup.png`),
  time: require(`${path}time.png`),
  users: require(`${path}users.png`),
  linesTitle: require(`${path}lines_title.png`),
  date: require(`${path}date.png`),
}